---
# tasks file for nginx
- name: Installing Nginx in Ubuntu
  apt: 
    name: nginx
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Installing Nginx in AWS 
  dnf:
    name: nginx
    state: present
  when: ansible_os_family == "RedHat"

- name: Copying website template for Ubuntu
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: Restart Nginx
  when: ansible_os_family == "Debian"

- name: Copying website template for AWS
  template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html
  notify: Restart Nginx
  when: ansible_os_family == "RedHat"

- name: start nginx
  service: 
    name: nginx
    state: started
    enabled: true 
